import {test,expect} from '@playwright/test';
test('member notes appear only after opening details and stay out of list search and CSV',async({page,baseURL})=>{
 if(baseURL!=='http://127.0.0.1:5173')throw Error('Local only');
 const id=Date.now().toString(),name='메모 확인 '+id,note='비공개메모'+id+' <b>일반 텍스트</b>';
 await page.goto('/admin');await page.getByRole('button',{name:'가상 임원으로 확인하기'}).click();await expect(page.getByRole('heading',{name:'운영 현황'})).toBeVisible();await page.goto('/admin/members?semester=2026-2');
 await page.getByRole('button',{name:'부원 등록',exact:true}).click();const d=page.getByRole('dialog');await d.locator('[name=name]').fill(name);await d.locator('[name=studentId]').fill(id);await d.locator('[name=phone]').fill('01012345678');await d.locator('[name=note]').fill(note);await d.getByRole('button',{name:'저장',exact:true}).click();await expect(d).toHaveCount(0);
 await expect(page.locator('main')).not.toContainText(note);await page.getByRole('searchbox',{name:'부원 검색'}).fill('비공개메모'+id);await expect(page.locator('#filter-empty')).toBeVisible();await page.getByRole('searchbox',{name:'부원 검색'}).fill('');
 await page.getByRole('button',{name,exact:true}).click();await expect(d).toContainText(note);await expect(d.locator('section b')).toHaveCount(0);await d.getByRole('button',{name:'정보 · 메모 수정'}).click();await expect(d.locator('[name=note]')).toHaveValue(note);await d.locator('[name=note]').fill(note+' 수정');await d.getByRole('button',{name:'저장',exact:true}).click();await expect(d).toHaveCount(0);
 await page.reload();await expect(page.locator('main')).not.toContainText(note);await page.getByRole('button',{name,exact:true}).click();await expect(d).toContainText(note+' 수정');await page.screenshot({path:'.local/screenshots/member-notes-'+test.info().project.name+'.jpg',type:'jpeg'});await d.getByRole('button',{name:'닫기',exact:true}).last().click();
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'CSV 내보내기'}).click();await d.locator('[name=reason]').fill('메모 제외 검증');await d.getByRole('button',{name:'저장',exact:true}).click();const download=await pending,stream=await download.createReadStream();let csv='';for await(const chunk of stream)csv+=chunk.toString('utf8');expect(csv).not.toContain('비공개메모');expect(csv).not.toContain('note');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
